#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use File::Basename qw(dirname);
use File::Path qw(make_path);

my $scene_path = 'build/generated.scene';
my $vector_path = 'build/generated_vectors.txt';
my $seed = 2026;
my $count = 128;
GetOptions(
    'scene=s'  => \$scene_path,
    'vectors=s'=> \$vector_path,
    'seed=i'   => \$seed,
    'count=i'  => \$count,
) or die "usage: $0 [--scene path] [--vectors path] [--seed n] [--count n]\n";
die "count must be positive\n" unless $count > 0;
srand($seed);

make_path(dirname($scene_path), dirname($vector_path));
open my $scene, '>', $scene_path or die "cannot write $scene_path: $!\n";
print {$scene} "# Deterministic scene generated by tools/gen_scene.pl\n";
print {$scene} "camera 0 1.3 6.4  0 0.2 -1  46\n";
print {$scene} "background 0.008 0.015 0.045\n";
print {$scene} "light -4 5 3  0.45 0.82 1.0  1.8\n";
print {$scene} "light 4 2 1  1.0 0.25 0.42  0.9\n";
for my $index (0 .. 6) {
    my $angle = 6.28318530718 * $index / 7;
    my $x = 2.25 * cos($angle);
    my $z = -1.2 + 1.35 * sin($angle);
    my $radius = 0.38 + 0.10 * ($index % 3);
    my ($r, $g, $b) = (0.16 + 0.11*$index, 0.82 - 0.07*$index, 0.95 - 0.05*$index);
    printf {$scene} "sphere %.4f %.4f %.4f %.4f  %.4f %.4f %.4f  %.3f\n",
        $x, -0.48 + $radius, $z, $radius, $r, $g, $b, 0.12 + 0.04*$index;
}
print {$scene} "plane 0 1 0 1.05  0.13 0.15 0.22  0.18\n";
close $scene;

sub signed_value { return int(rand(3073)) - 1536; }
sub nonzero_direction {
    my @d;
    do { @d = (signed_value(), signed_value(), signed_value()); }
    while ($d[0] == 0 && $d[1] == 0 && $d[2] == 0);
    return @d;
}

open my $vectors, '>', $vector_path or die "cannot write $vector_path: $!\n";
for (1 .. $count) {
    my @origin = (signed_value(), signed_value(), signed_value());
    my @direction = nonzero_direction();
    my @center = (signed_value(), signed_value(), signed_value());
    my $radius = 64 + int(rand(705));
    my @oc = map { $origin[$_] - $center[$_] } 0 .. 2;
    my $a = $direction[0]**2 + $direction[1]**2 + $direction[2]**2;
    my $half_b = $oc[0]*$direction[0] + $oc[1]*$direction[1] + $oc[2]*$direction[2];
    my $c = $oc[0]**2 + $oc[1]**2 + $oc[2]**2 - $radius**2;
    my $discriminant = $half_b**2 - $a*$c;
    my $hit = ($a > 0 && $discriminant >= 0 && ($half_b <= 0 || $c <= 0)) ? 1 : 0;
    print {$vectors} join(' ', @origin, @direction, @center, $radius, $hit), "\n";
}
close $vectors;
print "generated $scene_path and $vector_path ($count vectors, seed=$seed)\n";
